-- ============================================
-- INSERIR TODOS OS 80 PRODUTOS NO SUPABASE
-- Cole isto no SQL Editor do Supabase e clique RUN
-- ============================================

INSERT INTO cardapio (nome_item, categoria, descricao, precos, imagem_url, disponivel) VALUES
-- PIZZAS SALGADAS (43 itens)
('Costela', 'Salgadas', 'Costela desfiada, cebola, creme cheese, mussarela e barbecue.', '{"p": 35.00, "m": 45.00, "g": 65.00, "gg": null, "super": 80.00}', null, true),
('Calabresa Especial', 'Salgadas', 'Molho de tomate, calabresa fatiada, mussarela, creme cheese, barbecue, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 53.00, "gg": null, "super": 73.00}', null, true),
('Carne de Sol', 'Salgadas', 'Molho de tomate, carne de sol desfiada, cebola fatiada, mussarela, orégano e azeitonas.', '{"p": 34.00, "m": 44.00, "g": 60.00, "gg": null, "super": 80.00}', null, true),
('À Moda do Chefe', 'Salgadas', 'Molho de tomate, lombo canadense, bacon, mussarela, champignon, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 62.00, "gg": null, "super": 75.00}', null, true),
('Espanhola', 'Salgadas', 'Molho de tomate, calabresa moída, ovos cozidos, cebola, pimentão fatiado, mussarela, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 50.00, "gg": null, "super": 65.00}', null, true),
('Peperone', 'Salgadas', 'Molho de tomate, mussarela, salaminho tipo peperone, parmesão, orégano e azeitonas.', '{"p": 28.50, "m": 38.00, "g": 50.00, "gg": null, "super": 60.00}', null, true),
('Camarão', 'Salgadas', 'Molho de tomate, mussarela, filé de camarão, orégano e azeitonas.', '{"p": 35.00, "m": 45.00, "g": 62.00, "gg": null, "super": 80.00}', null, true),
('Frango Bolonhesa', 'Salgadas', 'Molho de tomate, frango desfiado, queijo parmesão, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 56.00, "gg": null, "super": 75.00}', null, true),
('Siciliana', 'Salgadas', 'Molho de tomate, mussarela, champignon.', '{"p": 28.00, "m": 38.00, "g": 50.00, "gg": null, "super": 70.00}', null, true),
('Nordestina', 'Salgadas', 'Molho de tomate, carne de charque desfiada, cebola, pimentão, pimenta de cheiro, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 62.00, "gg": null, "super": 80.00}', null, true),
('À Sua Moda', 'Salgadas', 'Ingredientes sugeridos pelo cliente.', '{"p": 35.00, "m": 45.00, "g": 64.00, "gg": null, "super": 80.00}', null, true),
('Vegetariana', 'Salgadas', 'Molho de tomate, mussarela, palmito, tomate fatiado, pimentão, champignon, manjericão, orégano e azeitonas.', '{"p": 30.00, "m": 40.00, "g": 48.00, "gg": null, "super": 60.00}', null, true),
('Caipira', 'Salgadas', 'Molho de tomate, frango desfiado, milho verde, catupiry, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 53.00, "gg": null, "super": 73.00}', null, true),
('Toscana', 'Salgadas', 'Molho de tomate, calabresa moída, cebola, mussarela, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 44.00, "gg": null, "super": 60.00}', null, true),
('4 Queijos', 'Salgadas', 'Molho de tomate, mussarela, provolone, catupiry, parmesão, orégano e azeitonas.', '{"p": 28.00, "m": 41.00, "g": 48.00, "gg": null, "super": 62.00}', null, true),
('À Moda do Forneiro', 'Salgadas', 'Molho de tomate, carne de sol desfiada, champignon, palmito, catupiry, manjericão, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 54.00, "gg": null, "super": 73.00}', null, true),
('Bolonhesa', 'Salgadas', 'Molho de tomate, mussarela, molho bolonhesa, parmesão, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 48.00, "gg": null, "super": 55.00}', null, true),
('Palmito', 'Salgadas', 'Molho de tomate, palmito picado e temperado, catupiry, mussarela, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 53.00, "gg": null, "super": 60.00}', null, true),
('À Moda do Pizzaiolo', 'Salgadas', 'Molho de tomate, presunto picado, palmito, ervilha, mussarela, bacon, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 52.00, "gg": null, "super": 73.00}', null, true),
('Marguerita', 'Salgadas', 'Molho de tomate, mussarela, manjericão, rodelas de tomate, parmesão, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 48.00, "gg": null, "super": 55.00}', null, true),
('Verona', 'Salgadas', 'Molho de tomate, palmito, bacon, catupiry, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 52.00, "gg": null, "super": 65.00}', null, true),
('Formágio', 'Salgadas', 'Molho de tomate, mussarela, provolone, catupiry, gorgonzola, parmesão, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 50.00, "gg": null, "super": 60.00}', null, true),
('Hot Dog', 'Salgadas', 'Salsicha, milho, catupiry, mussarela e batata palha.', '{"p": 28.00, "m": 38.00, "g": 47.00, "gg": null, "super": 60.00}', null, true),
('À Grega', 'Salgadas', 'Molho de tomate, mussarela, catupiry, calabresa fatiada, bacon, orégano e azeitonas.', '{"p": 28.00, "m": 41.00, "g": 56.00, "gg": null, "super": 61.00}', null, true),
('Napolitana', 'Salgadas', 'Molho de tomate, mussarela, rodelas de tomate, parmesão, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 45.00, "gg": null, "super": 54.00}', null, true),
('Atum', 'Salgadas', 'Molho de tomate, atum sólido, cebola, mussarela, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 45.00, "gg": null, "super": 65.00}', null, true),
('Atum c/ Cream Cheese', 'Salgadas', 'Molho de tomate, atum, cebola, cream cheese, orégano.', '{"p": 35.00, "m": 45.00, "g": 53.00, "gg": null, "super": 73.00}', null, true),
('Agreste', 'Salgadas', 'Molho de tomate, carne de charque desfiada, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 60.00, "gg": null, "super": 73.00}', null, true),
('Charque', 'Salgadas', 'Molho de tomate, carne de charque desfiada, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 60.00, "gg": null, "super": 73.00}', null, true),
('Suíça', 'Salgadas', 'Molho de tomate, presunto, mussarela, gorgonzola, orégano e azeitonas.', '{"p": 30.00, "m": 40.00, "g": 45.00, "gg": null, "super": 60.00}', null, true),
('Carne de Sol c/ Cream Cheese', 'Salgadas', 'Molho de tomate, carne de sol, cebola, orégano, Cream Cheese e Bacon Fatiado.', '{"p": 32.00, "m": 45.00, "g": 62.00, "gg": null, "super": 73.00}', null, true),
('Strogonoff', 'Salgadas', 'Molho de tomate, mussarela, strogonoff.', '{"p": 32.00, "m": 42.00, "g": 53.00, "gg": null, "super": 65.00}', null, true),
('Frango c/ Cream Cheese', 'Salgadas', 'Molho de tomate, frango desfiado, mussarela.', '{"p": 35.00, "m": 45.00, "g": 60.00, "gg": null, "super": 73.00}', null, true),
('Frango c/ Mussarela', 'Salgadas', 'Molho de tomate, frango desfiado, mussarela, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 55.00, "gg": null, "super": 75.00}', null, true),
('Frango c/ Catupiry', 'Salgadas', 'Molho de tomate, frango desfiado, catupiry, mussarela, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 55.00, "gg": null, "super": 75.00}', null, true),
('Bacon', 'Salgadas', 'Molho de tomate, mussarela, bacon, rodelas de tomate, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 55.00, "gg": null, "super": 70.00}', null, true),
('À Moda da Casa', 'Salgadas', 'Molho de tomate, frango desfiado, milho verde, mussarela, bacon, orégano e azeitonas.', '{"p": 32.00, "m": 42.00, "g": 62.00, "gg": null, "super": 80.00}', null, true),
('Francesa', 'Salgadas', 'Molho de tomate, presunto, ovos, cebola, ervilha, catupiry, orégano e azeitonas.', '{"p": 30.00, "m": 40.00, "g": 50.00, "gg": null, "super": 65.00}', null, true),
('Mussarela', 'Salgadas', 'Molho de tomate, mussarela, rodelas de tomate, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 44.00, "gg": null, "super": 54.00}', null, true),
('Calabresa', 'Salgadas', 'Molho de tomate, calabresa, mussarela, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 46.00, "gg": null, "super": 60.00}', null, true),
('Portuguesa', 'Salgadas', 'Molho de tomate, presunto, ovos, cebola, mussarela, orégano e azeitonas.', '{"p": 30.00, "m": 40.00, "g": 50.00, "gg": null, "super": 65.00}', null, true),
('Bauru', 'Salgadas', 'Molho de tomate, presunto, mussarela, rodelas de tomate, orégano e azeitonas.', '{"p": 28.00, "m": 38.00, "g": 44.00, "gg": null, "super": 60.00}', null, true),
-- PIZZAS DOCES (5 itens)
('Chocolate com Morango', 'Doces', 'Chocolate com morango.', '{"p": 30.00, "m": 35.00, "g": 40.00, "gg": 54.00}', null, true),
('Banana Nevada', 'Doces', 'Banana com canela, creme de leite e chocolate branco com borda de doce de leite.', '{"p": 30.00, "m": 35.00, "g": 40.00, "gg": 54.00}', null, true),
('Cartola', 'Doces', 'Mussarela, catupiry, banana fatiada, açúcar e canela com borda de doce de leite.', '{"p": 30.00, "m": 35.00, "g": 40.00, "gg": 54.00}', null, true),
('Romeu e Julieta', 'Doces', 'Mussarela coberta com fatia de goiabada, com borda de doce de leite.', '{"p": 30.00, "m": 35.00, "g": 40.00, "gg": 54.00}', null, true),
('Dois Amores', 'Doces', 'Chocolate branco e chocolate de avelã com borda de doce de leite.', '{"p": 30.00, "m": 35.00, "g": 40.00, "gg": 54.00}', null, true),
-- MASSAS (4 itens)
('Espaguete', 'Massas', 'Serve 1 pessoa. Monte sua massa escolhendo molho e até 6 ingredientes.', '{"p": 26.00}', null, true),
('Parafuso', 'Massas', 'Serve 1 pessoa. Monte sua massa escolhendo molho e até 6 ingredientes.', '{"p": 26.00}', null, true),
('Penne', 'Massas', 'Serve 1 pessoa. Monte sua massa escolhendo molho e até 6 ingredientes.', '{"p": 26.00}', null, true),
('Rigatoni', 'Massas', 'Serve 1 pessoa. Monte sua massa escolhendo molho e até 6 ingredientes.', '{"p": 26.00}', null, true),
-- PASTÉIS (8 itens)
('Pastel de Queijo', 'Pastéis de Forno', 'Pastel crocante recheado com queijo derretido.', '{"p": 15.00}', null, true),
('Pastel de Carne', 'Pastéis de Forno', 'Pastel crocante recheado com carne moída e temperos.', '{"p": 15.00}', null, true),
('Pastel de Frango', 'Pastéis de Forno', 'Pastel crocante recheado com frango desfiado.', '{"p": 15.00}', null, true),
('Pastel de Calabresa', 'Pastéis de Forno', 'Pastel crocante recheado com calabresa e queijo.', '{"p": 15.00}', null, true),
('Pastel de Presunto', 'Pastéis de Forno', 'Pastel crocante recheado com presunto e queijo.', '{"p": 15.00}', null, true),
('Pastel de Espinafre', 'Pastéis de Forno', 'Pastel crocante recheado com espinafre e queijo.', '{"p": 15.00}', null, true),
('Pastel de Brócolis', 'Pastéis de Forno', 'Pastel crocante recheado com brócolis e queijo.', '{"p": 15.00}', null, true),
('Pastel Mix', 'Pastéis de Forno', 'Pastel crocante com mix de recheios deliciosos.', '{"p": 16.00}', null, true),
-- LASANHAS (4 itens)
('Lasanha à Bolonhesa', 'Lasanhas', 'Lasanha caseira com molho bolonhesa, mussarela e parmesão.', '{"m": 32.00}', null, true),
('Lasanha 4 Queijos', 'Lasanhas', 'Lasanha caseira com 4 tipos de queijo derretido.', '{"m": 32.00}', null, true),
('Lasanha de Frango', 'Lasanhas', 'Lasanha caseira com frango desfiado e molho branco.', '{"m": 32.00}', null, true),
('Lasanha de Brócolis', 'Lasanhas', 'Lasanha caseira com brócolis, molho branco e queijo.', '{"m": 32.00}', null, true),
-- CALZONES (6 itens)
('Calzone Calabresa', 'Calzones', 'Pizza fechada recheada com calabresa, mussarela e cebola.', '{"p": 32.00, "m": 42.00, "g": 52.00}', null, true),
('Calzone Mussarela', 'Calzones', 'Pizza fechada recheada com mussarela fresca e orégano.', '{"p": 28.00, "m": 38.00, "g": 48.00}', null, true),
('Calzone Frango', 'Calzones', 'Pizza fechada recheada com frango desfiado e catupiry.', '{"p": 32.00, "m": 42.00, "g": 52.00}', null, true),
('Calzone 4 Queijos', 'Calzones', 'Pizza fechada recheada com mix de 4 queijos.', '{"p": 32.00, "m": 42.00, "g": 52.00}', null, true),
('Calzone Portuguesa', 'Calzones', 'Pizza fechada recheada com presunto, ovo, cebola e mussarela.', '{"p": 30.00, "m": 40.00, "g": 50.00}', null, true),
('Calzone Costela', 'Calzones', 'Pizza fechada recheada com costela desfiada e creme cheese.', '{"p": 35.00, "m": 45.00, "g": 55.00}', null, true),
-- PETISCOS (6 itens)
('Asinhas de Frango', 'Petiscos', 'Asinhas de frango temperadas e assadas na brasa.', '{"m": 28.00}', null, true),
('Bolinha de Queijo', 'Petiscos', 'Bolinhas crocantes de queijo derretido por dentro.', '{"m": 24.00}', null, true),
('Batata Frita', 'Petiscos', 'Batata frita crocante e saborosa.', '{"m": 18.00}', null, true),
('Aros de Cebola', 'Petiscos', 'Aros de cebola empanados e fritos até ficar crocante.', '{"m": 20.00}', null, true),
('Linguiça Grelhada', 'Petiscos', 'Linguiça fina grelhada e temperada.', '{"m": 26.00}', null, true),
('Cubos de Queijo', 'Petiscos', 'Cubos de queijo empanados e fritos.', '{"m": 22.00}', null, true),
-- BEBIDAS (5 itens)
('Refrigerante 2L', 'Bebidas', 'Refrigerante gelado (Coca-Cola, Guaraná ou Fanta).', '{"m": 12.00}', null, true),
('Suco Natural', 'Bebidas', 'Suco natural fresco de frutas da estação.', '{"m": 10.00}', null, true),
('Água', 'Bebidas', 'Água mineral geladinha.', '{"m": 3.00}', null, true),
('Cerveja 350ml', 'Bebidas', 'Cerveja gelada importada ou local.', '{"m": 8.00}', null, true),
('Chopp 1L', 'Bebidas', 'Chopp gelado direto do barril.', '{"m": 25.00}', null, true);
